# Generated by Django 3.1.1 on 2020-09-25 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.FloatField()),
                ('limiteSaqueDiario', models.FloatField()),
                ('flagAtivo', models.BooleanField(default=True)),
                ('tipoConta', models.IntegerField()),
                ('dataCriacao', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11)),
                ('dataNascimento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('dataTransacao', models.DateField()),
                ('idConta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_management_api.account')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='idPessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_management_api.person'),
        ),
    ]
